
---
- name: Securely reset root password
  hosts: all
  become: yes
  become_user: root
  vars_files:
    - vault.yml
  tasks:
    - name: Set root password
      user:
        name: root
        password: "{{ vault_root_password }}"
